### ISSUE TITLE
Noy working with MyFrama

### ISSUE THREAD

**Issue by jaj42** [dimtion/Shaarlier#25] opened 2016-11-27 08:00 UTC
Hi, maybe a PEBKEC but I cannot make this work with the MyFrama public shaarli instance. I tried http://my.framasoft.org/ with different settings but shaarlier says the url is not working.
Best regards, Jona

**Comment by dimtion** [comment] 2017-02-26 17:57
I'll have a look as soon as possible.

**Comment by dimtion** [comment] 2017-02-26 18:10
I could not reproduced the bug with these settings :
```
url : https://my.framasoft.org/u/dimtion/
username : dimtion
password : ****
No HTTP Auth
```


You should try with the `https` protocol as : https://my.framasoft.org/. And maybe not forget the final `/`

**Comment by freayd** [comment] 2017-04-09 10:50
It also works fine for me. The login process is actually described in the [Framablog post](https://framablog.org/2016/10/10/myframa-vos-favoris-et-framasofteries-partout-avec-vous-rien-qua-vous/).

**Comment by dimtion** [comment] 2017-05-02 10:49
@jaj42 have you got any update on this ? Otherwise I'll close the issue.

**Comment by dimtion** [comment] 2017-07-08 20:45
/

**Closed as completed by dimtion** 2017-07-08 20:45 UTC
Labels: invalid, question
